### ISSUE TITLE
Using binary serialization/deserialization will leak metadata

### ISSUE THREAD

**Issue by romanholidaypancakes** [stephenberry/glaze#827] opened 2024-03-13 12:17 UTC
It can infer complete information about the original structure

https://gcc.godbolt.org/z/q69WKPa64

It seems to be related to  [glaze/reflection/get_name.hpp](https://github.com/stephenberry/glaze/blob/main/include/glaze/reflection/get_name.hpp)

I'm not familiar with the internal design principles of this library. I guess this string is used as the unique ID to determine the member fields of the structure? But it was mistakenly retained in the binary. Maybe we can calculate the hash of this string at compile time to determine the uniqueness of the structure field? Maybe I guessed wrong.

![image](https://github.com/stephenberry/glaze/assets/51652878/5f33407e-f1aa-4704-8773-5dbcdcb4a721)

**Comment by stephenberry** [comment] 2024-03-13 14:40
Thanks for bringing this up. We should be able to compile-time stack allocate only the portion we need, which should allow the binary to not include these long strings. The issue is that we are currently using a `std::string_view` to a small portion of these strings and the compiler isn't smart enough to only store what is needed.

This is being used to reflect on struct member names. When using `glz::meta` to define the reflection it shouldn't call `get_name`, but I did a little test with compiler explorer and it somehow still generates these strings even though it never needs to: https://gcc.godbolt.org. I'll look into this more when I'm able. Fixing this should reduce binary size.

**Comment by stephenberry** [comment] 2024-03-13 14:43
I just realized that if you provide your own names in `glz::meta` then these strings won't be generated and you won't leak types, if you're worried about that.

```c++
template <>
struct glz::meta<my_struct>
{
    using T = my_struct;
    static constexpr auto value = object("i", &T::i, "d", &T::d, "hello", &T::hello, "arr", &T::arr, "map", &T::map);
};
```

https://gcc.godbolt.org

**Comment by stephenberry** [comment] 2024-03-14 13:57
You're correct that the static memory is what is keeping the symbols inside the binary. It currently must do this if we use pure reflection because we aren't allocating (on the stack in the binary) just the names, so the string_views are referring to a portion of the entire prettified function signature. I think we can avoid this by stack allocating just the names we want so that the compiler will optimize away the longer name.

Your comment that `struct glz::meta<my_struct>` also leaks variable names is a little confused. The binary must contain the names if it is to read and write JSON. A very simple hello world example will include `"Hello World"` in the binary: https://gcc.godbolt.org

The purpose of Glaze is to match JSON to C++ so that you don't need additional indirection. If you need to hide variable names from your binary you could map your structures with pointers that have externally facing names, but it is important to understand that wherever you use strings (c style) in your code, those strings will be baked into the binary, because they must be a part of the program.

**Comment by stephenberry** [comment] 2024-03-14 14:03
A better way (than pointer indirection) of hiding your variable names would just be to use different names in your `glz::meta`:

```c++
template <>
struct glz::meta<my_struct>
{
    using T = my_struct;
    static constexpr auto value = object("int", &T::i, "double", &T::d, "Hello", &T::hello, "Array", &T::arr, "MyMap", &T::map);
};
```

Obviously these new names will exist in the binary, but not your actual variable names.

**Comment by stephenberry** [comment] 2024-03-15 12:27
The current binary format in Glaze is [BEVE](https://github.com/stephenberry/beve). The purpose of this format is to allow the data to match JSON, so that it can be converted back and forth. And, this allows data to be introspected and used without a schema. This is the default encoding of structures in Glaze.

However, Glaze also supports encoding structs as BEVE arrays, which uses indices for the keys rather than the ascii names.
Here is an example using the option `structs_as_arrays`, which will not expose the ascii field names: https://gcc.godbolt.org/z/dhGY4PTdY

I think this is what you're looking for.

**Comment by stephenberry** [comment] 2024-03-15 13:27
Excellent. You can keep this issue open because it's revealed some ways to improve the generated binary.

**Comment by stephenberry** [comment] 2024-04-18 11:27
Glaze now makes a static, compile time string from only the key in the mangled reflected name. The binary is reduced and only holds the key names unless `structs_as_arrays` is set to true, in which case no keys will be included.

The original test case shows this: https://gcc.godbolt.org/z/q69WKPa64

Thanks for bringing up this issue as we now have smaller binary produced.

**Closed by stephenberry** 2024-04-18 11:27 UTC
Labels: enhancement
