### ISSUE TITLE
[BUG?] Build fails on latest version (using g++)

### ISSUE THREAD

**Issue by edunad** [stephenberry/glaze#1196] opened 2024-07-22 08:51 UTC
I'm using the latest version (v3.1.5) and the CI/CD is throwing some glaze errors, it's building fine on windows
https://github.com/edunad/rawrbox/actions/runs/10037621909/job/27737794760#step:7:352

Using the following struct and passing it down to a template
```c++
struct TestSettingsData {
	std::string VERSION = "0.0.2";

	std::map<std::string, float> video = {{"scale", 0.5F}, {"monitor", 2.F}};
	std::map<std::string, std::string> controls = {{"jump", "A"}, {"crouch", "L_CNTRL"}};

	std::string username = "MISSING";
};
```

(i also added requires guards `write_json_supported` and `read_json_supported` and they pass fine)

https://github.com/edunad/rawrbox/blob/features/popup/rawrbox.utils/include/rawrbox/utils/settings.hpp#L14
https://github.com/edunad/rawrbox/blob/features/popup/rawrbox.utils/tests/settings.spec.cpp#L6

**Comment by stephenberry** [comment] 2024-07-22 14:51
I added test cases for this use case in #1201 and they pass with GCC 12, 13, and 14. I think the problem is that your CI/CD is using GCC 11, which hasn't been supported for a while and now fails all the time with Glaze version 3 and beyond.

So, I think it is a compiler bug that I don't expect will be fixed in GCC 11.

**Closed** 2024-07-22 14:52 UTC
