### ISSUE TITLE
size_t wraparound causes huge allocation when reading generic json 

### ISSUE THREAD

**Issue by pauldreik** [stephenberry/glaze#1204] opened 2024-07-23 12:17 UTC
The following test (sorry, not minimized):

```cpp
   "blaha2"_test = []() {
      glz::json_t json{};

      std::vector<unsigned char> udata{
         0x22, 0x5c, 0x75, 0x22, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65,
         0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65,
         0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65,
         0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65,
         0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65,
         0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x65, 0x4b, 0x00};
      std::vector<unsigned char> data{udata.begin(), udata.end()};
      auto r = glz::read_json(json, data);
      expect(r);
   };

```

causes an exception to be thrown by std::string trying to allocate 2**64-1 bytes. I found that the size n gets bad at this line: https://github.com/stephenberry/glaze/blob/25483f44dc913f090990c7182255b4e03b741587/include/glaze/json/read.hpp#L761

**Comment by stephenberry** [comment] 2024-07-23 14:22
This issue was caused by an invalid check on the hex digits of the unicode parse. It has been fixed in #1205, the amusing thing is that the correct test is actually more efficient.

Thanks for the bug report!

**Closed** 2024-07-23 14:29 UTC
