### ISSUE TITLE
Write_binary/read_binary support for the "json_t" interface

### ISSUE THREAD

**Issue by meftunca** [stephenberry/glaze#1081] opened 2024-06-12 15:29 UTC
Write_binary/read_binary support for the "json_t" interface. My problem logs are below 

```bash
external/_main~conan_extension~glaze/include/glaze/binary/write.hpp:115:13: error: implicit instantiation of undefined template 'glz::detail::to_binary<std::variant<std::nullptr_t, double, std::string, bool, std::vector<glz::json_t>, std::map<std::string, glz::json_t, std::less<void>>> &>'
            to_binary<V>::template op<Opts>(get_member(value, meta_wrapper_v<T>), std::forward<Args>(args)...);
            ^
external/_main~conan_extension~glaze/include/glaze/binary/write.hpp:96:57: note: in instantiation of function template specialization 'glz::detail::to_binary<glz::json_t>::op<{0, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, glz::context &, std::vector<std::byte> &, unsigned long &, glz::json_t &>' requested here
            to_binary<std::remove_cvref_t<T>>::template op<Opts>(std::forward<T>(value), std::forward<Ctx>(ctx),
                                                        ^
external/_main~conan_extension~glaze/include/glaze/binary/write.hpp:513:34: note: in instantiation of function template specialization 'glz::detail::write<0>::op<{0, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, glz::json_t &, glz::context &, std::vector<std::byte> &, unsigned long &>' requested here
                  write<binary>::op<Opts>(x, ctx, args...);
                                 ^
external/_main~conan_extension~glaze/include/glaze/binary/write.hpp:96:57: note: in instantiation of function template specialization 'glz::detail::to_binary<std::vector<glz::json_t>>::op<{0, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<std::byte> &, unsigned long &, std::vector<glz::json_t> &, glz::context &>' requested here
            to_binary<std::remove_cvref_t<T>>::template op<Opts>(std::forward<T>(value), std::forward<Ctx>(ctx),
                                                        ^
external/_main~conan_extension~glaze/include/glaze/core/write.hpp:24:44: note: in instantiation of function template specialization 'glz::detail::write<0>::op<{0, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<glz::json_t> &, glz::context &, std::vector<std::byte> &, unsigned long &>' requested here
      detail::write<Opts.format>::template op<Opts>(std::forward<T>(value), ctx, buffer, ix);
                                           ^
external/_main~conan_extension~glaze/include/glaze/core/write.hpp:56:14: note: in instantiation of function template specialization 'glz::write<{0, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<glz::json_t> &, std::vector<std::byte>, glz::context &>' requested here
      return write<Opts>(std::forward<T>(value), buffer, ctx);
             ^
external/_main~conan_extension~glaze/include/glaze/binary/write.hpp:911:14: note: in instantiation of function template specialization 'glz::write<{0, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<glz::json_t> &, std::vector<std::byte>>' requested here
      return write<opts{.format = binary}>(std::forward<T>(value), std::forward<Buffer>(buffer));
             ^
src/resourcesPool/memoizedFile.cc:100:25: note: in instantiation of function template specialization 'glz::write_binary<std::vector<glz::json_t> &, std::vector<std::byte> &>' requested here
         auto ec = glz::write_binary(m_json_, data);
                        ^
external/_main~conan_extension~glaze/include/glaze/core/opts.hpp:210:14: note: template is declared here
      struct to_binary;
             ^
```

Error line 
```bash
external/_main~conan_extension~glaze/include/glaze/binary/write.hpp:115:13: error: implicit instantiation of undefined template 'glz::detail::to_binary<std::variant<std::nullptr_t, double, std::string, bool, std::vector<glz::json_t>, std::map<std::string, glz::json_t, std::less<void>>> &>'
            to_binary<V>::template op<Opts>(get_member(value, meta_wrapper_v<T>), std::forward<Args>(args)...);```

**Comment by meftunca** [comment] 2024-06-12 15:32
I also get this error when I want to write for ndjson

``` bash
external/_main~conan_extension~glaze/include/glaze/util/dtoa.hpp:998:20: error: assigning to 'std::byte' from incompatible type 'char'
         *buffer = '-';
                   ^~~
external/_main~conan_extension~glaze/include/glaze/core/write_chars.hpp:88:38: note: in instantiation of function template specialization 'glz::to_chars<double, std::byte>' requested here
               const auto end = glz::to_chars(start, value);
                                     ^
external/_main~conan_extension~glaze/include/glaze/json/write.hpp:225:29: note: in instantiation of function template specialization 'glz::detail::write_chars::op<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<std::byte> &, double &, glz::context &, unsigned long &>' requested here
               write_chars::op<Opts>(value, ctx, b, ix);
                            ^
external/_main~conan_extension~glaze/include/glaze/json/write.hpp:31:55: note: in instantiation of function template specialization 'glz::detail::to_json<double>::op<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<std::byte> &, double &, glz::context &, unsigned long &>' requested here
            to_json<std::remove_cvref_t<T>>::template op<Opts>(std::forward<T>(value), std::forward<Ctx>(ctx),
                                                      ^
external/_main~conan_extension~glaze/include/glaze/json/write.hpp:854:35: note: in instantiation of function template specialization 'glz::detail::write<10>::op<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, double &, glz::context &, std::vector<std::byte> &, unsigned long &>' requested here
                     write<json>::op<Opts>(val, ctx, args...);
                                  ^
external/_main~conan_extension~glaze/include/glaze/json/write.hpp:44:34: note: in instantiation of function template specialization 'glz::detail::to_json<std::variant<std::nullptr_t, double, std::string, bool, std::vector<glz::json_t>, std::map<std::string, glz::json_t, std::less<void>>>>::op<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<std::byte> &, unsigned long &, std::variant<std::nullptr_t, double, std::string, bool, std::vector<glz::json_t>, std::map<std::string, glz::json_t, std::less<void>>> &, glz::context &>' requested here
            to_json<V>::template op<Opts>(get_member(std::forward<Value>(value), meta_wrapper_v<T>),
                                 ^
external/_main~conan_extension~glaze/include/glaze/json/write.hpp:31:55: note: (skipping 2 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
            to_json<std::remove_cvref_t<T>>::template op<Opts>(std::forward<T>(value), std::forward<Ctx>(ctx),
                                                      ^
external/_main~conan_extension~glaze/include/glaze/json/ndjson.hpp:161:50: note: in instantiation of function template specialization 'glz::detail::to_ndjson<std::vector<glz::json_t>>::op<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<std::byte> &, unsigned long &, std::vector<glz::json_t> &, glz::context &>' requested here
            to_ndjson<std::decay_t<T>>::template op<Opts>(std::forward<T>(value), std::forward<Ctx>(ctx),
                                                 ^
external/_main~conan_extension~glaze/include/glaze/core/write.hpp:24:44: note: in instantiation of function template specialization 'glz::detail::write<100>::op<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<glz::json_t> &, glz::context &, std::vector<std::byte> &, unsigned long &>' requested here
      detail::write<Opts.format>::template op<Opts>(std::forward<T>(value), ctx, buffer, ix);
                                           ^
external/_main~conan_extension~glaze/include/glaze/core/write.hpp:56:14: note: in instantiation of function template specialization 'glz::write<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<glz::json_t> &, std::vector<std::byte>, glz::context &>' requested here
      return write<Opts>(std::forward<T>(value), buffer, ctx);
             ^
external/_main~conan_extension~glaze/include/glaze/json/ndjson.hpp:298:14: note: in instantiation of function template specialization 'glz::write<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<glz::json_t> &, std::vector<std::byte>>' requested here
      return write<opts{.format = ndjson}>(std::forward<T>(value), std::forward<Buffer>(buffer));
             ^
src/resourcesPool/memoizedFile.cc:99:22: note: in instantiation of function template specialization 'glz::write_ndjson<std::vector<glz::json_t> &, std::vector<std::byte> &>' requested here
      auto ec = glz::write_ndjson(m_json_, data);
                     ^
In file included from src/resourcesPool/memoizedFile.cc:1:
In file included from ./src/resourcesPool/memoizedFile.h:6:
In file included from external/_main~conan_extension~glaze/include/glaze/glaze.hpp:35:
In file included from external/_main~conan_extension~glaze/include/glaze/binary.hpp:6:
In file included from external/_main~conan_extension~glaze/include/glaze/binary/custom.hpp:6:
In file included from external/_main~conan_extension~glaze/include/glaze/binary/read.hpp:7:
In file included from external/_main~conan_extension~glaze/include/glaze/binary/skip.hpp:8:
In file included from external/_main~conan_extension~glaze/include/glaze/core/read.hpp:9:
In file included from external/_main~conan_extension~glaze/include/glaze/core/common.hpp:27:
In file included from external/_main~conan_extension~glaze/include/glaze/util/validate.hpp:10:
In file included from external/_main~conan_extension~glaze/include/glaze/core/write_chars.hpp:11:
external/_main~conan_extension~glaze/include/glaze/util/dtoa.hpp:903:16: error: assigning to 'std::byte' from incompatible type 'uint8_t' (aka 'unsigned char')
      buf[0] = uint8_t(a + '0');
               ^~~~~~~~~~~~~~~~
external/_main~conan_extension~glaze/include/glaze/util/dtoa.hpp:1041:31: note: in instantiation of function template specialization 'glz::write_u64_len_15_to_17_trim<std::byte>' requested here
               auto num_end = write_u64_len_15_to_17_trim(num_hdr, sig_dec);
                              ^
external/_main~conan_extension~glaze/include/glaze/core/write_chars.hpp:88:38: note: in instantiation of function template specialization 'glz::to_chars<double, std::byte>' requested here
               const auto end = glz::to_chars(start, value);
                                     ^
external/_main~conan_extension~glaze/include/glaze/json/write.hpp:225:29: note: in instantiation of function template specialization 'glz::detail::write_chars::op<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<std::byte> &, double &, glz::context &, unsigned long &>' requested here
               write_chars::op<Opts>(value, ctx, b, ix);
                            ^
external/_main~conan_extension~glaze/include/glaze/json/write.hpp:31:55: note: in instantiation of function template specialization 'glz::detail::to_json<double>::op<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<std::byte> &, double &, glz::context &, unsigned long &>' requested here
            to_json<std::remove_cvref_t<T>>::template op<Opts>(std::forward<T>(value), std::forward<Ctx>(ctx),
                                                      ^
external/_main~conan_extension~glaze/include/glaze/json/write.hpp:854:35: note: in instantiation of function template specialization 'glz::detail::write<10>::op<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, double &, glz::context &, std::vector<std::byte> &, unsigned long &>' requested here
                     write<json>::op<Opts>(val, ctx, args...);
                                  ^
external/_main~conan_extension~glaze/include/glaze/json/write.hpp:44:34: note: (skipping 3 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
            to_json<V>::template op<Opts>(get_member(std::forward<Value>(value), meta_wrapper_v<T>),
                                 ^
external/_main~conan_extension~glaze/include/glaze/json/ndjson.hpp:161:50: note: in instantiation of function template specialization 'glz::detail::to_ndjson<std::vector<glz::json_t>>::op<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<std::byte> &, unsigned long &, std::vector<glz::json_t> &, glz::context &>' requested here
            to_ndjson<std::decay_t<T>>::template op<Opts>(std::forward<T>(value), std::forward<Ctx>(ctx),
                                                 ^
external/_main~conan_extension~glaze/include/glaze/core/write.hpp:24:44: note: in instantiation of function template specialization 'glz::detail::write<100>::op<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<glz::json_t> &, glz::context &, std::vector<std::byte> &, unsigned long &>' requested here
      detail::write<Opts.format>::template op<Opts>(std::forward<T>(value), ctx, buffer, ix);
                                           ^
external/_main~conan_extension~glaze/include/glaze/core/write.hpp:56:14: note: in instantiation of function template specialization 'glz::write<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<glz::json_t> &, std::vector<std::byte>, glz::context &>' requested here
      return write<Opts>(std::forward<T>(value), buffer, ctx);
             ^
external/_main~conan_extension~glaze/include/glaze/json/ndjson.hpp:298:14: note: in instantiation of function template specialization 'glz::write<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<glz::json_t> &, std::vector<std::byte>>' requested here
      return write<opts{.format = ndjson}>(std::forward<T>(value), std::forward<Buffer>(buffer));
             ^
src/resourcesPool/memoizedFile.cc:99:22: note: in instantiation of function template specialization 'glz::write_ndjson<std::vector<glz::json_t> &, std::vector<std::byte> &>' requested here
      auto ec = glz::write_ndjson(m_json_, data);
                     ^
In file included from src/resourcesPool/memoizedFile.cc:1:
In file included from ./src/resourcesPool/memoizedFile.h:6:
In file included from external/_main~conan_extension~glaze/include/glaze/glaze.hpp:35:
In file included from external/_main~conan_extension~glaze/include/glaze/binary.hpp:6:
In file included from external/_main~conan_extension~glaze/include/glaze/binary/custom.hpp:6:
In file included from external/_main~conan_extension~glaze/include/glaze/binary/read.hpp:7:
In file included from external/_main~conan_extension~glaze/include/glaze/binary/skip.hpp:8:
In file included from external/_main~conan_extension~glaze/include/glaze/core/read.hpp:9:
In file included from external/_main~conan_extension~glaze/include/glaze/core/common.hpp:27:
In file included from external/_main~conan_extension~glaze/include/glaze/util/validate.hpp:10:
In file included from external/_main~conan_extension~glaze/include/glaze/core/write_chars.hpp:11:
external/_main~conan_extension~glaze/include/glaze/util/dtoa.hpp:1042:28: error: assigning to 'std::byte' from incompatible type 'char'
               buffer[0] = '0';
                           ^~~
external/_main~conan_extension~glaze/include/glaze/core/write_chars.hpp:88:38: note: in instantiation of function template specialization 'glz::to_chars<double, std::byte>' requested here
               const auto end = glz::to_chars(start, value);
                                     ^
external/_main~conan_extension~glaze/include/glaze/json/write.hpp:225:29: note: in instantiation of function template specialization 'glz::detail::write_chars::op<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<std::byte> &, double &, glz::context &, unsigned long &>' requested here
               write_chars::op<Opts>(value, ctx, b, ix);
                            ^
external/_main~conan_extension~glaze/include/glaze/json/write.hpp:31:55: note: in instantiation of function template specialization 'glz::detail::to_json<double>::op<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<std::byte> &, double &, glz::context &, unsigned long &>' requested here
            to_json<std::remove_cvref_t<T>>::template op<Opts>(std::forward<T>(value), std::forward<Ctx>(ctx),
                                                      ^
external/_main~conan_extension~glaze/include/glaze/json/write.hpp:854:35: note: in instantiation of function template specialization 'glz::detail::write<10>::op<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, double &, glz::context &, std::vector<std::byte> &, unsigned long &>' requested here
                     write<json>::op<Opts>(val, ctx, args...);
                                  ^
external/_main~conan_extension~glaze/include/glaze/json/write.hpp:44:34: note: in instantiation of function template specialization 'glz::detail::to_json<std::variant<std::nullptr_t, double, std::string, bool, std::vector<glz::json_t>, std::map<std::string, glz::json_t, std::less<void>>>>::op<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<std::byte> &, unsigned long &, std::variant<std::nullptr_t, double, std::string, bool, std::vector<glz::json_t>, std::map<std::string, glz::json_t, std::less<void>>> &, glz::context &>' requested here
            to_json<V>::template op<Opts>(get_member(std::forward<Value>(value), meta_wrapper_v<T>),
                                 ^
external/_main~conan_extension~glaze/include/glaze/json/write.hpp:31:55: note: (skipping 2 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
            to_json<std::remove_cvref_t<T>>::template op<Opts>(std::forward<T>(value), std::forward<Ctx>(ctx),
                                                      ^
external/_main~conan_extension~glaze/include/glaze/json/ndjson.hpp:161:50: note: in instantiation of function template specialization 'glz::detail::to_ndjson<std::vector<glz::json_t>>::op<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<std::byte> &, unsigned long &, std::vector<glz::json_t> &, glz::context &>' requested here
            to_ndjson<std::decay_t<T>>::template op<Opts>(std::forward<T>(value), std::forward<Ctx>(ctx),
                                                 ^
external/_main~conan_extension~glaze/include/glaze/core/write.hpp:24:44: note: in instantiation of function template specialization 'glz::detail::write<100>::op<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<glz::json_t> &, glz::context &, std::vector<std::byte> &, unsigned long &>' requested here
      detail::write<Opts.format>::template op<Opts>(std::forward<T>(value), ctx, buffer, ix);
                                           ^
external/_main~conan_extension~glaze/include/glaze/core/write.hpp:56:14: note: in instantiation of function template specialization 'glz::write<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<glz::json_t> &, std::vector<std::byte>, glz::context &>' requested here
      return write<Opts>(std::forward<T>(value), buffer, ctx);
             ^
external/_main~conan_extension~glaze/include/glaze/json/ndjson.hpp:298:14: note: in instantiation of function template specialization 'glz::write<{100, false, true, true, true, false, false, 32, 3, true, false, true, false, false, false, 0, 0, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, true, false, false, false}, std::vector<glz::json_t> &, std::vector<std::byte>>' requested here
      return write<opts{.format = ndjson}>(std::forward<T>(value), std::forward<Buffer>(buffer));
             ^
src/resourcesPool/memoizedFile.cc:99:22: note: in instantiation of function template specialization 'glz::write_ndjson<std::vector<glz::json_t> &, std::vector<std::byte> &>' requested here
      auto ec = glz::write_ndjson(m_json_, data);
                     ^
In file included from src/resourcesPool/memoizedFile.cc:1:
In file included from ./src/resourcesPool/memoizedFile.h:6:
In file included from external/_main~conan_extension~glaze/include/glaze/glaze.hpp:35:
In file included from external/_main~conan_extension~glaze/include/glaze/binary.hpp:6:
In file included from external/_main~conan_extension~glaze/include/glaze/binary/custom.hpp:6:
In file included from external/_main~conan_extension~glaze/include/glaze/binary/read.hpp:7:
In file included from external/_main~conan_extension~glaze/include/glaze/binary/skip.hpp:8:
In file included from external/_main~conan_extension~glaze/include/glaze/core/read.hpp:9:
In file included from external/_main~conan_extension~glaze/include/glaze/core/common.hpp:27:
In file included from external/_main~conan_extension~glaze/include/glaze/util/validate.hpp:10:
In file included from external/_main~conan_extension~glaze/include/glaze/core/write_chars.hpp:11:
external/_main~conan_extension~glaze/include/glaze/util/dtoa.hpp:1043:28: error: assigning to 'std::byte' from incompatible type 'char'
               buffer[1] = '.';
```

**Comment by stephenberry** [comment] 2024-06-13 12:31
The issue is actually not with ndjson, but with writing to `std::vector<std::byte>`. I've fixed this in #1089 and will merge soon.

I still have to fix binary support for `glz::json_t`

**Comment by meftunca** [comment] 2024-06-13 12:57
I see. Do you have an estimate for the completion date for Binary?

**Comment by stephenberry** [comment] 2024-06-13 13:11
Binary support should get merged in the next hour.

**Comment by stephenberry** [comment] 2024-06-13 13:21
Binary support for `json_t` has been merged

**Closed** 2024-06-13 13:21 UTC
Labels: bug

**Comment by meftunca** [comment] 2024-06-13 14:31
You're really fast :D
